### ISSUE TITLE
[BUG] panic if invidious has popular feed disable

### ISSUE THREAD

**Issue by LuckyTurtleDev** [Siriusmart/youtube-tui#26]
Youtube-tui does panic if invidious has popular feed disable:
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/items/itemlist.rs:42:16
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
If I enable the popular feed at server youtube-tui does work again.
I have try to disable popular at the `page,yml` but this has not fix the problem.

`main.yml`:
```yml
mouse_support: true
invidious_instance: https://youtube.luckyturtle.dev
max_watch_history: 50
allow_unicode: true
message_bar_default: All good :)
images: Sixels
refresh_after_modifying_search_filters: true
image_index: 4
provider: YouTube
env:
  terminal-emulator: alacritty -e
  video-player: mpv
  download-path: '''~/Downloads/%(title)s-%(id)s.%(ext)s'''
  youtube-downloader: yt-dlp
  browser: firefox
```

`pages.yml`:
```yml
main_menu:
  layout:
  - type: NonCenteredRow
    items:
    - SearchBar
    - SearchFilters
  - type: CenteredRow
    items:
   # - Popular
    - Trending
    - History
  - type: NonCenteredRow
    items:
    - ItemList
  - type: NonCenteredRow
    items:
    - MessageBar
  message: Loading main menu...
search:
  layout:
  - type: NonCenteredRow
    items:
    - SearchBar
    - SearchFilters
  - type: NonCenteredRow
    items:
    - ItemList
  - type: NonCenteredRow
    items:
    - MessageBar
  message: Loading search results...
singleitem:
  layout:
  - type: NonCenteredRow
    items:
    - SearchBar
    - SearchFilters
  - type: NonCenteredRow
    items:
    - SingleItemInfo
  - type: NonCenteredRow
    items:
    - MessageBar
  message: Loading item details...
channeldisplay:
  layout:
  - type: NonCenteredRow
    items:
    - SearchBar
    - SearchFilters
  - type: CenteredRow
    items:
    - ChannelMain
    - ChannelVideos
    - ChannelPlaylists
  - type: NonCenteredRow
    items:
    - ChannelDisplay
  - type: NonCenteredRow
    items:
    - MessageBar
  message: Loading channel details...
```
